"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.toast = exports.tooltip = exports.RadioGroup = exports.Toggle = exports.Window = exports.Timepicker = exports.Tree = exports.Toolbar = exports.Textarea = exports.Tabs = exports.Message = exports.InputNumber = exports.InputText = exports.InputDate = exports.InputTime = exports.Form = exports.Datagrid = exports.Button = exports.Box = exports.MultiCombobox = exports.Combobox = void 0;
require("./assets/fontello/css/fontello.css");
require("./style.css");
const Box_1 = require("./box/Box");
Object.defineProperty(exports, "Box", { enumerable: true, get: function () { return Box_1.Box; } });
const Button_1 = require("./controls/button/Button");
Object.defineProperty(exports, "Button", { enumerable: true, get: function () { return Button_1.Button; } });
const Datagrid_1 = require("./datagrid/Datagrid");
Object.defineProperty(exports, "Datagrid", { enumerable: true, get: function () { return Datagrid_1.Datagrid; } });
const Tabs_1 = require("./tabs/Tabs");
Object.defineProperty(exports, "Tabs", { enumerable: true, get: function () { return Tabs_1.Tabs; } });
const Toolbar_1 = require("./toolbar/Toolbar");
Object.defineProperty(exports, "Toolbar", { enumerable: true, get: function () { return Toolbar_1.Toolbar; } });
const Tree_1 = require("./tree/Tree");
Object.defineProperty(exports, "Tree", { enumerable: true, get: function () { return Tree_1.Tree; } });
const Tooltip_1 = require("./messages/Tooltip");
const Toast_1 = require("./messages/Toast");
const Message_1 = require("./messages/Message");
Object.defineProperty(exports, "Message", { enumerable: true, get: function () { return Message_1.Message; } });
const Window_1 = require("./window/Window");
Object.defineProperty(exports, "Window", { enumerable: true, get: function () { return Window_1.Window; } });
const InputTime_1 = require("./editors/input/InputTime");
Object.defineProperty(exports, "InputTime", { enumerable: true, get: function () { return InputTime_1.InputTime; } });
const InputDate_1 = require("./editors/input/InputDate");
Object.defineProperty(exports, "InputDate", { enumerable: true, get: function () { return InputDate_1.InputDate; } });
const InputNumber_1 = require("./editors/input/InputNumber");
Object.defineProperty(exports, "InputNumber", { enumerable: true, get: function () { return InputNumber_1.InputNumber; } });
const InputText_1 = require("./editors/input/InputText");
Object.defineProperty(exports, "InputText", { enumerable: true, get: function () { return InputText_1.InputText; } });
const Form_1 = require("./form/Form");
Object.defineProperty(exports, "Form", { enumerable: true, get: function () { return Form_1.Form; } });
const Textarea_1 = require("./editors/textarea/Textarea");
Object.defineProperty(exports, "Textarea", { enumerable: true, get: function () { return Textarea_1.Textarea; } });
const MultiCombobox_1 = require("./editors/combobox/MultiCombobox");
Object.defineProperty(exports, "MultiCombobox", { enumerable: true, get: function () { return MultiCombobox_1.MultiCombobox; } });
const Combobox_1 = require("./editors/combobox/Combobox");
Object.defineProperty(exports, "Combobox", { enumerable: true, get: function () { return Combobox_1.Combobox; } });
const Timepicker_1 = require("./timepicker/Timepicker");
Object.defineProperty(exports, "Timepicker", { enumerable: true, get: function () { return Timepicker_1.Timepicker; } });
const Toggle_1 = require("./editors/toggle/Toggle");
Object.defineProperty(exports, "Toggle", { enumerable: true, get: function () { return Toggle_1.Toggle; } });
const RadioGroup_1 = require("./editors/radio-group/RadioGroup");
Object.defineProperty(exports, "RadioGroup", { enumerable: true, get: function () { return RadioGroup_1.RadioGroup; } });
const tooltip = Tooltip_1.Tooltip.show;
exports.tooltip = tooltip;
const toastInstance = new Toast_1.Toast();
const toast = (config) => toastInstance.show(config);
exports.toast = toast;
